name: "0) Start Release - minor version"

on:
  workflow_dispatch:

permissions: write-all

jobs:
  update-version-and-open-pull-request-:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get current version and bump minor
        id: version
        run: |
          # Get current version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"

          # Bump minor version using npm
          npm version minor --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")

          echo "New version: $NEW_VERSION"
          echo "RELEASE_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "BRANCH_NAME=release/$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create release branch
        run: |
          git checkout -b ${{ steps.version.outputs.BRANCH_NAME }}

      - name: Commit version bump
        run: |
          git add package.json
          git commit -m "chore: bump version to ${{ steps.version.outputs.RELEASE_VERSION }}"

      - name: Push release branch
        run: |
          git push origin ${{ steps.version.outputs.BRANCH_NAME }}

      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            if git ls-remote --exit-code origin "refs/heads/${{ steps.version.outputs.BRANCH_NAME }}"; then
              echo "Branch ${{ steps.version.outputs.BRANCH_NAME }} already exists on remote. Deleting it..."
              git push origin :"${{ steps.version.outputs.BRANCH_NAME }}"
            fi

            // Get the latest release to find when it was created
            let lastReleaseDate = null;
            try {
              const { data: latestRelease } = await github.rest.repos.getLatestRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
              lastReleaseDate = new Date(latestRelease.published_at || latestRelease.created_at);
              console.log(`Last release date: ${lastReleaseDate}`);
            } catch (error) {
              console.log('No previous release found, will include all merged PRs');
              // Set to a very old date to include all PRs if no previous release
              lastReleaseDate = new Date('2015-01-01');
            }

            // Get all merged PRs
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              base: 'main',
              sort: 'updated',
              direction: 'desc',
              per_page: 100
            });

            console.log(`Found ${pullRequests.length} closed PRs`);

            // Filter for merged PRs since last release
            const mergedPRs = pullRequests.filter(pr => {
              if (!pr.merged_at) return false;
              const mergedDate = new Date(pr.merged_at);
              const isAfterLastRelease = mergedDate > lastReleaseDate;
              console.log(`PR #${pr.number}: merged ${mergedDate}, after last release: ${isAfterLastRelease}`);
              return isAfterLastRelease;
            });

            console.log(`Found ${mergedPRs.length} merged PRs since last release`);

            // Format PR list
            let prList = '';
            if (mergedPRs.length > 0) {
              prList = mergedPRs
                .sort((a, b) => a.merged_at - b.merged_at) // Sort by PR merged_at ascending
                .map(pr => `#${pr.number} — ${pr.title}`)
                .join('\n');
            } else {
              prList = 'No merged pull requests found since last release.';
            }

            console.log(`PR List:\n${prList}`);

            const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '${{ steps.version.outputs.RELEASE_VERSION }} Release',
              head: '${{ steps.version.outputs.BRANCH_NAME }}',
              base: 'main',
              body: `## Release ${{ steps.version.outputs.RELEASE_VERSION }}

              This PR contains the version bump for release ${{ steps.version.outputs.RELEASE_VERSION }}.

              ### Changes
              - Bumped version to ${{ steps.version.outputs.RELEASE_VERSION }}

              ### Merged Pull Requests
              ${prList}`,
            });

            // Add release label
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequest.number,
              labels: ['release']
            });

            console.log(`Created PR #${pullRequest.number}: ${pullRequest.html_url}`);
