name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - release/*

jobs:
  build:
    if: (github.event_name == 'pull_request' && github.event.pull_request.draft == false) || github.event_name == 'push'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        registry-url: 'https://registry.npmjs.org'
    - name: Yarn Install
      run: yarn
    - name: Yarn Lint
      run: yarn lint
